name: Run Gradle
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      CIWORKFLOW: yes
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: check -x groovydoc
    - name: Test simple
      working-directory: examples/simple
      run: |
        ./gradlew xslt xquery
    - name: Test jexec
      working-directory: examples/jexec
      run: |
        ./gradlew xslt xquery
    - name: Test depends
      working-directory: examples/depends
      run: |
        ./gradlew --console plain xslt xquery --stacktrace
